use Bank;

--CREATE TABLE PASSPORT (
--	NUMBER int PRIMARY KEY,
--	EXPIRES_DATE date NOT NULL
--);

CREATE TABLE ACCOUNT_OWNER (
	OWNER_ID int IDENTITY(1,1) PRIMARY KEY,
	PASSPORT_NUMBER int UNIQUE,
	BIRTH_DATE date NOT NULL,
	SURNAME varchar(30) NOT NULL,
	NAME varchar(30) NOT NULL,
	PATRONIMIC varchar(30) NOT NULL
);

CREATE TABLE ACCOUNT (
	NUMBER int PRIMARY KEY,
	ACCOUNT_OWNER int CONSTRAINT OWNER_FK FOREIGN KEY REFERENCES ACCOUNT_OWNER(OWNER_ID),
	DEPOSIT_TYPE varchar(30),
	BALANCE money CHECK (BALANCE >= 0) default(0) NOT NULL,
	OPENING_DATE date default(GETDATE()) NOT NULL,
	NOTIFICATIONS varchar(3) CHECK (NOTIFICATIONS IN ('on', 'off')) default('off'),
	INTERNET_BANKING varchar(3) CHECK (INTERNET_BANKING IN ('on', 'off')) default('off'),
	CLIENT_IMAGE varbinary(max)
);